### ISSUE TITLE
Error loading on Windows (or WSL Ubuntu) in compiler.js

### ISSUE THREAD

**Issue by zengland78** [oslabs-beta/navigate#125]
See the below error when running directly on Windows (which has no config to a running k8s cluster) or in Ubuntu under WSL2 on Windows with xserver vcxsrv.
See stack trace below and I will attach a screen shot of "empty" navigate.

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/mnt/c/work/workspaces/navigate/navigate/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/mnt/c/work/workspaces/navigate/navigate/node_modules/webpack/lib/util/createHash.js:80:21)
    at /mnt/c/work/workspaces/navigate/navigate/node_modules/webpack/lib/DefinePlugin.js:595:38
    at _next27 (eval at create (/mnt/c/work/workspaces/navigate/navigate/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:36:1)
    at _next5 (eval at create (/mnt/c/work/workspaces/navigate/navigate/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/mnt/c/work/workspaces/navigate/navigate/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:111:1)
    at Hook.CALL_DELEGATE [as _call] (/mnt/c/work/workspaces/navigate/navigate/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/mnt/c/work/workspaces/navigate/navigate/node_modules/webpack/lib/Compiler.js:1053:26) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by zengland78** [comment]
![navigate](https://user-images.githubusercontent.com/79376261/140650164-e1949805-473c-42c8-83f8-801815480488.PNG)

**Comment by brkg** [comment]
Thanks for opening this up. This should be addressed in my latest PR, going to link it in a moment
